services:
  prichexy-net:
    build: .
    image: prichexy-net:latest
    container_name: prichexy-net
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - .:/workspace
      - F:/datasets/datasets/nih-chest-xrays/data/versions/3/images:/data/images
    working_dir: /workspace
    stdin_open: true
    tty: true
    shm_size: '8gb'
