"""Run a full adaptive re-ID arm (STAGE A-E) for the frozen protocol.

Structure (see adaptive_reid/pipeline.py):
    STAGE A:  train + validate every restart (subprocess retrain_SNN.py per seed)
    STAGE B:  classify numerical validity + near-chance
    STAGE C:  select representative using VALIDATION AUC only
    STAGE D:  persist representative identity into provenance
    STAGE E:  evaluate frozen test pairs once per completed attacker

Determinism guarantee: seeds are taken from the schedule (ascending, internal), never
chosen by the user after seeing outcomes. Test evaluation is ALWAYS deferred to Stage E,
which is gated behind a --stage flag so representativeness is frozen first.

STEP 2B.1 remediation invariants:
    - EXACTLY ONE training invocation per seed. The scheduler (restarts.run_schedule)
      decides which seed to attempt, invokes the training worker once, and reads the
      final health state to decide replacements. No later stage re-trains.
    - Idempotent reuse: a completed (seed, config, protocol, artifacts) run is reused,
      never re-trained, unless --force is given.
    - No fabricated test metrics: a real (non-stub) Stage E has no implementation yet and
      raises NotImplementedError instead of emitting a made-up AUC. Stub outputs are
      explicitly marked stub/synthetic/valid_for_scientific_reporting=false (R-11).

Usage (production, AFTER the strict stop is lifted):
    python run_adaptive_reid_arm.py --mode confirmatory \
        --arm_id arm_corrected_mu0.01 \
        --checkpoint ./archive/.../generator_lowest_total_loss.pth \
        --transform_mode corrected --mu 0.01 \
        --out_dir ./archive/adaptive_reid_arms/arm_corrected_mu0.01 \
        --stage a_d

Use --stub to run the full staged pipeline on generated (non-trained) records; this is
the wrapper the test suite calls to verify stage-ordering without a GPU run.
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

from adaptive_reid import constants as C
from adaptive_reid import diagnostics as diag
from adaptive_reid import health
from adaptive_reid import provenance
from adaptive_reid import restarts
from adaptive_reid import summary as summ
from adaptive_reid import topk
from adaptive_reid import weights as ar_weights
from adaptive_reid import pipeline

PAIR_TRAIN = 'image_pairs/image_pairs_training_10000.txt'
PAIR_VAL = 'image_pairs/image_pairs_validation_2000.txt'
PAIR_TEST = 'image_pairs/image_pairs_testing_5000.txt'

CONFIG_TEMPLATE = './config_files/config_retrainSNN.json'

# Authoritative frozen artifacts (R-12 / amendment §2). These files are SOURCE OF
# TRUTH: they are never regenerated by this driver, only hashed into provenance.
PROTOCOL_01 = 'research_agent/01_ADAPTIVE_REID_PROTOCOL.md'
PROTOCOL_01B = 'research_agent/01B_PROTOCOL_AMENDMENT.md'
FROZEN_TOPK_CSV = 'research_agent/topk_frozen_list.csv'

SIGNATURE_FILENAME = 'run_signature.json'
ARCHIVE_ROOT = 'archive'


def attacker_checkpoint_path(seed):
    """Path of the canonical attacker checkpoint for a seed (matches the agent's save).

    The agent persists ``<experiment_description>_best_network.pth`` under
    ``./archive/<experiment_description>/`` where ``experiment_description`` is
    ``retrain_snn_seed{seed}`` for protocol attempts.
    """
    exp = 'retrain_snn_seed{}'.format(seed)
    return os.path.join(ARCHIVE_ROOT, exp, exp + '_best_network.pth')


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def git_commit():
    try:
        out = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True)
        return out.stdout.strip()
    except Exception:
        return 'unknown'


def hashes_for(paths):
    out = {}
    for p in paths:
        out[p] = diag.sha256_file(p) if os.path.exists(p) else ''
    return out


def protocol_and_frozen_hashes():
    protocol_documents = hashes_for([PROTOCOL_01, PROTOCOL_01B])
    frozen_artifacts = hashes_for([FROZEN_TOPK_CSV])
    # A-1: provenance must never record a non-frozen Top-k digest. Fail loudly if the
    # canonical artifact is missing or differs from the hard-pinned digest.
    if frozen_artifacts.get(FROZEN_TOPK_CSV) != topk.FROZEN_TOPK_SHA256:
        raise RuntimeError(
            'frozen Top-k digest mismatch: provenance would record %r, expected %r'
            % (frozen_artifacts.get(FROZEN_TOPK_CSV), topk.FROZEN_TOPK_SHA256))
    return protocol_documents, frozen_artifacts


def run_signature(seed, args, cfg, pair_hashes, protocol_documents, frozen_artifacts):
    """Deterministic identity of one restart attempt (used for idempotent reuse).

    D-1 (content pinning): the signature depends on BOTH the generator checkpoint
    path AND its SHA-256 computed from the actual checkpoint bytes. Two checkpoints
    with the same path but different bytes therefore produce DIFFERENT signatures,
    so a run trained against G_old is never reused once the path holds G_new.
    """
    return {
        'arm_id': args.arm_id,
        'attacker_seed': int(seed),
        'transform_mode': args.transform_mode,
        'mu': float(args.mu),
        'stochastic_lambda': float(getattr(args, 'stochastic_lambda', 0.0)),
        'generator_checkpoint_path': args.checkpoint,
        'generator_checkpoint_hash': _generator_hash(args),
        'pair_train_hash': pair_hashes.get(PAIR_TRAIN, ''),
        'pair_validation_hash': pair_hashes.get(PAIR_VAL, ''),
        'config': {
            'learning_rate': cfg.get('learning_rate'),
            'batch_size': cfg.get('batch_size'),
            'max_epochs': cfg.get('max_epochs'),
            'early_stopping': cfg.get('early_stopping'),
        },
        'protocol_documents': protocol_documents,
        'frozen_artifacts': frozen_artifacts,
        'stub': bool(args.stub),
    }


def reuse_completed_run(run_dir, signature, seed, args):
    """Return the persisted training diagnostics iff a completed, matching run exists.

    Idempotency (R-4 / BLOCKER 2B): a run whose training diagnostics, run state, and
    run signature all exist AND whose signature matches the current (seed, config,
    protocol, artifacts) is reused instead of being re-trained. For real runs the
    checkpoint must also exist AND be loadable. Returns None when the run must be
    (re)trained.

    D-1 (content pinning): the recorded ``generator_checkpoint_hash`` in the stored
    training diagnostics must equal the current arm's generator digest. A stale
    digest (same path, different bytes) forces retraining - never silent reuse.
    """
    diag_path = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    runstate_path = os.path.join(run_dir, diag.RUNSTATE_FILENAME)
    sig_path = os.path.join(run_dir, SIGNATURE_FILENAME)
    if not (os.path.exists(diag_path) and os.path.exists(runstate_path)
            and os.path.exists(sig_path)):
        return None
    try:
        stored = diag.read_json(sig_path)
    except Exception:
        return None
    if stored != signature:
        return None
    if not args.stub:
        ck = attacker_checkpoint_path(seed)
        # A completed real run must have a loadable checkpoint, not merely a
        # directory (STEP 2B.2: reuse must verify the persisted artifact set is real).
        if not ar_weights.checkpoint_loadable(ck):
            return None
    stored_diag = diag.read_json(diag_path)
    # D-1: reject stale generator content even if the signature were forged.
    if stored_diag.get('generator_checkpoint_hash', '') != signature.get('generator_checkpoint_hash', ''):
        return None
    return stored_diag


def stub_test_metrics(seed):
    """Deterministic synthetic Stage-E metric, EXPLICITLY marked non-scientific (R-11)."""
    return {
        'auc': 0.5 + 0.01 * (seed % 7),
        'stub': True,
        'synthetic': True,
        'valid_for_scientific_reporting': False,
        'note': 'STUB SYNTHETIC smoke metric - not a measured privacy result',
    }


def require_real_test_eval(stub):
    """Refuse to fabricate test AUC: only a stub may emit synthetic metrics (R-11)."""
    if not stub:
        raise NotImplementedError(
            'STAGE E real test evaluation is not implemented in STEP 2B.1. '
            'Refusing to fabricate a test AUC. Either run with --stub (synthetic, '
            'marked non-scientific) or implement the real frozen-test evaluation.')


def write_arm_provenance(arm_id, out_dir, summary, attempts, args, cfg, pair_hashes,
                         t0, t1, commit):
    run_states = {a['attacker_seed']: a['state'] for a in attempts}
    near_flags = {a['attacker_seed']: a['near_chance'] for a in attempts}
    seeds_attempted = [a['attacker_seed'] for a in attempts]
    rep = summary.get('representative_attacker_seed')
    protocol_documents, frozen_artifacts = protocol_and_frozen_hashes()
    record = provenance.build_arm_provenance(
        arm_id=arm_id, git_commit=commit, transform_mode=args.transform_mode,
        generator_checkpoint_path=args.checkpoint,
        generator_checkpoint_hash=diag.sha256_file(args.checkpoint) if args.checkpoint and os.path.exists(args.checkpoint) else '',
        mu=args.mu, stochastic_lambda=getattr(args, 'stochastic_lambda', 0.0),
        attacker_architecture='ResNet-50 Siamese',
        attacker_hyperparameters={
            'learning_rate': cfg.get('learning_rate'),
            'batch_size': cfg.get('batch_size'),
            'max_epochs': cfg.get('max_epochs'),
            'early_stopping': cfg.get('early_stopping'),
        },
        attacker_seeds_attempted=seeds_attempted,
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL, pair_test_path=PAIR_TEST,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        pair_test_hash=pair_hashes.get(PAIR_TEST, ''),
        representative_attacker_seed=rep,
        representative_selection_criterion='best-validation-AUC closest to median, tie=smaller seed',
        run_states=run_states, near_chance_flags=near_flags,
        run_start_timestamp=t0, run_end_timestamp=t1, schedule_name=args.mode,
        protocol_documents=protocol_documents, frozen_artifacts=frozen_artifacts)
    diag.write_json(os.path.join(out_dir, 'arm_provenance.json'), record)
    return record


def verify_stage_e_generator_hash(run_dir, seed, current_hash):
    """D-1: refuse Stage E evaluation when the recorded generator digest is stale.

    :raises RuntimeError: missing diagnostics or recorded digest != current arm digest.
    """
    diag_path = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    if not os.path.exists(diag_path):
        raise RuntimeError('Stage E refused: missing training_diagnostics for seed %d' % seed)
    recorded = diag.read_json(diag_path).get('generator_checkpoint_hash', '')
    if recorded != current_hash:
        raise RuntimeError(
            'Stage E refused: recorded generator_checkpoint_hash %r does not match '
            'current arm generator_checkpoint_hash %r for seed %d'
            % (recorded, current_hash, seed))


def main():
    parser = argparse.ArgumentParser('Adaptive re-ID arm (frozen protocol)')
    parser.add_argument('--mode', choices=['screening', 'confirmatory'], required=True)
    parser.add_argument('--arm_id', required=True)
    parser.add_argument('--checkpoint', default=None)
    parser.add_argument('--transform_mode', default='legacy', choices=['legacy', 'corrected'])
    parser.add_argument('--mu', type=float, default=0.01)
    parser.add_argument('--stochastic_lambda', type=float, default=0.0)
    parser.add_argument('--out_dir', required=True)
    parser.add_argument('--base_config', default=CONFIG_TEMPLATE)
    parser.add_argument('--stage', choices=['a_d', 'a_e'], default='a_d',
                        help="'a_d' trains+classifies+selects+persists representative "
                             "(NO test eval). 'a_e' additionally runs Stage E test eval.")
    parser.add_argument('--stub', action='store_true',
                        help='Generate stub records instead of launching retrain_SNN.exe '
                             '(no GPU, for tests/CI). Stub test metrics are explicitly '
                             'marked synthetic and can never enter a scientific summary.')
    parser.add_argument('--force', action='store_true',
                        help='Re-train even if a matching completed run is present '
                             '(explicit override of idempotent reuse).')
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    t0 = now_iso()

    with open(args.base_config) as f:
        cfg = json.load(f)

    pair_hashes = hashes_for([PAIR_TRAIN, PAIR_VAL, PAIR_TEST])
    protocol_documents, frozen_artifacts = protocol_and_frozen_hashes()

    commit = git_commit()
    schedule = (restarts.ScreeningSchedule() if args.mode == 'screening'
                else restarts.ConfirmatorySchedule())

    # ---- Stage A + B worker: EXACTLY ONE training invocation per seed attempt ----
    def train_and_report(seed):
        exp = 'retrain_snn_seed{}'.format(seed)
        run_dir = os.path.join(args.out_dir, 'runs', exp)
        os.makedirs(run_dir, exist_ok=True)
        start = now_iso()

        signature = run_signature(seed, args, cfg, pair_hashes,
                                  protocol_documents, frozen_artifacts)
        diag.write_json(os.path.join(run_dir, SIGNATURE_FILENAME), signature)

        if not args.force:
            reused = reuse_completed_run(run_dir, signature, seed, args)
            if reused is not None:
                rec = reused
            else:
                rec = _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes,
                                  protocol_documents, frozen_artifacts)
        else:
            rec = _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes,
                              protocol_documents, frozen_artifacts)
        rec['run_end_timestamp'] = now_iso()
        diag.write_json(os.path.join(run_dir, diag.VALIDITY_FILENAME), rec)

        state, near = health.classify_run_health(rec)
        validation_record = _validation_record_from(rec)

        diag.write_json(os.path.join(run_dir, diag.RUNSTATE_FILENAME),
                        {'state': state, 'near_chance': near, 'evaluated_test': False})
        return {'attacker_seed': seed, 'state': state, 'near_chance': near,
                'diagnostics': rec, 'validation_record': validation_record,
                'run_dir': run_dir}

    def evaluate_test(seed):
        # Stage E: evaluate the frozen TEST pairs exactly once for this completed attacker.
        require_real_test_eval(args.stub)
        run_dir = os.path.join(args.out_dir, 'runs', 'retrain_snn_seed{}'.format(seed))
        # D-1: never evaluate a run whose recorded generator digest is stale relative to
        # the current arm. Refuse loudly rather than silently repairing provenance.
        verify_stage_e_generator_hash(run_dir, seed, _generator_hash(args))
        metrics = stub_test_metrics(seed)
        diag_path = os.path.join(run_dir, diag.TESTMETRICS_FILENAME)
        diag.write_json(diag_path, {**metrics, 'evaluation_timestamp': now_iso()})
        return metrics

    # The scheduler trains each attempted seed exactly once (Stage A) and, from the
    # final health state, issues ascending replacement seeds (Stage B loop).
    attempts = restarts.run_schedule(schedule, train_and_report)

    pl = pipeline.ArmPipeline(
        train_validate_and_persist=lambda seed: train_and_report(seed),
        evaluate_test=evaluate_test if args.stage == 'a_e' else None)
    # NOTE: stage_a_train_all is intentionally NOT called here - it would re-train every
    # restart (BLOCKER 2). The schedule already trained each seed exactly once.
    pl.stage_b_classify(attempts)
    rep_seed = pl.stage_c_select_representative(attempts)
    mark = {}
    pl.stage_d_persist_representative(attempts, rep_seed, mark)

    summary = summ.summarize_arm(attempts)
    summary['representative_attacker_seed'] = rep_seed
    if args.stage == 'a_e':
        pl.stage_e_evaluate_test(attempts)
        summary = summ.summarize_arm(attempts)
        summary['representative_attacker_seed'] = rep_seed

    t1 = now_iso()
    prov = write_arm_provenance(args.arm_id, args.out_dir, summary, attempts, args, cfg,
                                pair_hashes, t0, t1, commit)
    diag.write_json(os.path.join(args.out_dir, 'arm_summary.json'), summary)

    # A-1: frozen Top-k is hard-pinned. Canonical loading requires the exact tracked
    # path, fails loudly if missing or digest-mismatched, and NEVER regenerates.
    frozen = topk.load_frozen_topk_list_canonical(FROZEN_TOPK_CSV,
                                                  expected_sha256=topk.FROZEN_TOPK_SHA256)
    topk.save_frozen_topk_list(os.path.join(args.out_dir, topk.FROZEN_LIST_FILENAME), frozen)

    print('ARM COMPLETE: %s' % args.arm_id)
    print('representative_attacker_seed:', rep_seed)
    print(json.dumps(summary, indent=2, sort_keys=True))
    print('provenance:', os.path.join(args.out_dir, 'arm_provenance.json'))


def _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes,
                protocol_documents=None, frozen_artifacts=None):
    """Launch the single training invocation for one seed and return its record.

    STEP 2B.2: the real training loop (retrain_SNN.py -> AgentSiameseNetwork) now
    persists its own training_diagnostics.json into ``run_dir`` when the config carries
    ``training_diagnostics_path``, ``evaluate_test_after_training`` and the provenance
    hashes. We pass exactly those keys so the diagnostics contain the real run's values
    (loss curves, AUC/accuracy, best epochs, termination reason, NaN/Inf, parameter
    hashes, checkpoint loadability, protocol/frozen hashes) and never any test metric.

    Raises RuntimeError instead of fabricating a record when a real run finishes without
    the protocol's machine-readable diagnostics file (no invented diagnostics).
    """
    if args.stub:
        return _stub_record(seed, start, run_dir, cfg, args, pair_hashes,
                            ck_exists=args.stub and seed % 5 != 2,
                            protocol_documents=protocol_documents,
                            frozen_artifacts=frozen_artifacts)
    scfg = dict(cfg)
    scfg['experiment_description'] = exp
    scfg['seed'] = seed
    scfg['transform_mode'] = args.transform_mode
    scfg['mu'] = args.mu
    scfg['stochastic_lambda'] = args.stochastic_lambda
    scfg['evaluate_test_after_training'] = False
    scfg['training_diagnostics_path'] = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    scfg['pair_train_path'] = PAIR_TRAIN
    scfg['pair_validation_path'] = PAIR_VAL
    scfg['pair_train_hash'] = pair_hashes.get(PAIR_TRAIN, '')
    scfg['pair_validation_hash'] = pair_hashes.get(PAIR_VAL, '')
    scfg['protocol_documents'] = protocol_documents or {}
    scfg['frozen_artifacts'] = frozen_artifacts or {}
    if args.checkpoint:
        scfg['perturbation_model_file'] = args.checkpoint
        scfg['generator_checkpoint_hash'] = diag.sha256_file(args.checkpoint) if os.path.exists(args.checkpoint) else ''
    else:
        scfg['generator_checkpoint_hash'] = ''
    cfg_path = os.path.join('config_files', exp + '.json')
    with open(cfg_path, 'w') as f:
        json.dump(scfg, f, indent=2)
    res = subprocess.run(
        [sys.executable, 'retrain_SNN.py', '--config_path', './config_files/',
         '--config', exp + '.json'], cwd=os.getcwd())
    os.remove(cfg_path) if os.path.exists(cfg_path) else None
    if res.returncode != 0:
        return _infra_record(seed, start, run_dir, cfg, args, pair_hashes,
                             protocol_documents=protocol_documents,
                             frozen_artifacts=frozen_artifacts)
    diag_path = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    if os.path.exists(diag_path):
        return diag.read_json(diag_path)
    # rc==0 but no diagnostics file: the real training loop did not persist the
    # protocol record. This is an objective execution failure, not a valid completed
    # run - record infrastructure_failure rather than fabricate metrics or crash the
    # whole arm (STEP 2B.2 task 6). The schedule then issues a replacement seed.
    print('WARNING: seed %d rc=0 but no %s in %s; recording infrastructure failure'
          % (seed, diag.VALIDITY_FILENAME, run_dir))
    return _infra_record(seed, start, run_dir, cfg, args, pair_hashes,
                         protocol_documents=protocol_documents,
                         frozen_artifacts=frozen_artifacts)


def _generator_hash(args):
    """sha256 of the generator checkpoint actually used, or '' when absent."""
    ck = getattr(args, 'checkpoint', None)
    if ck and os.path.exists(ck):
        return diag.sha256_file(ck)
    return ''


def _stub_record(seed, start, run_dir, cfg, args, pair_hashes, ck_exists=True,
                 protocol_documents=None, frozen_artifacts=None):
    # deterministic stub: seed%5==2 marks infrastructure failure (no checkpoint)
    epochs = 8
    val_loss = [0.62 + (seed % 3) * 0.02] * epochs
    val_auc = [0.55 + (seed % 4) * 0.03] * epochs
    val_acc = [0.55] * epochs
    loss = [0.60] * epochs
    if seed % 5 == 2:
        val_loss = [0.75] * epochs
        val_auc = [0.50] * epochs
    return diag.build_training_diagnostics(
        attacker_seed=seed, transform_mode=args.transform_mode, mu=args.mu,
        stochastic_lambda=args.stochastic_lambda,
        generator_checkpoint_path=args.checkpoint or '',
        generator_checkpoint_hash=_generator_hash(args),
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        epochs_completed=epochs, termination_reason=C.TERMINATION_EARLY_STOPPING,
        training_loss_per_epoch=loss, validation_loss_per_epoch=val_loss,
        validation_auc_per_epoch=val_auc, validation_accuracy_per_epoch=val_acc,
        best_validation_loss=min(val_loss), best_validation_loss_epoch=int(np_val_loss(val_loss)),
        best_validation_auc=max(val_auc), best_validation_auc_epoch=int(np_val_auc(val_auc)),
        any_nan_inf=False, checkpoint_exists=ck_exists, checkpoint_loadable=ck_exists,
        weights_changed_from_initialization=ck_exists,
        protocol_documents=protocol_documents or {}, frozen_artifacts=frozen_artifacts or {},
        run_start_timestamp=start, run_end_timestamp=now_iso())


def _infra_record(seed, start, run_dir, cfg, args, pair_hashes,
                  protocol_documents=None, frozen_artifacts=None):
    return diag.build_training_diagnostics(
        attacker_seed=seed, transform_mode=args.transform_mode, mu=args.mu,
        stochastic_lambda=args.stochastic_lambda,
        generator_checkpoint_path=args.checkpoint or '',
        generator_checkpoint_hash=_generator_hash(args),
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        epochs_completed=0, termination_reason=C.TERMINATION_INFRASTRUCTURE,
        training_loss_per_epoch=[], validation_loss_per_epoch=[],
        validation_auc_per_epoch=[], validation_accuracy_per_epoch=[],
        best_validation_loss=float('inf'), best_validation_loss_epoch=-1,
        best_validation_auc=0.0, best_validation_auc_epoch=-1,
        any_nan_inf=True, checkpoint_exists=False, checkpoint_loadable=False,
        weights_changed_from_initialization=False,
        protocol_documents=protocol_documents or {}, frozen_artifacts=frozen_artifacts or {},
        run_start_timestamp=start, run_end_timestamp=now_iso())


def _validation_record_from(rec):
    return {'attacker_seed': rec['attacker_seed'],
            'validation_auc_per_epoch': list(rec['validation_auc_per_epoch']),
            'validation_loss_per_epoch': list(rec['validation_loss_per_epoch']),
            'validation_accuracy_per_epoch': list(rec['validation_accuracy_per_epoch'])}


def np_val_loss(a):
    return min(range(len(a)), key=lambda i: a[i])


def np_val_auc(a):
    return max(range(len(a)), key=lambda i: a[i])


if __name__ == '__main__':
    main()
