"""Run a full adaptive re-ID arm (STAGE A-E) for the frozen protocol.

Structure (see adaptive_reid/pipeline.py):
    STAGE A:  train + validate every restart (subprocess retrain_SNN.py per seed)
    STAGE B:  classify numerical validity + near-chance
    STAGE C:  select representative using VALIDATION AUC only
    STAGE D:  persist representative identity into provenance
    STAGE E:  evaluate frozen test pairs once per completed attacker

Determinism guarantee: seeds are taken from the schedule (ascending, internal), never
chosen by the user after seeing outcomes. Test evaluation is ALWAYS deferred to Stage E,
which is gated behind a --stage flag so representativeness is frozen first.

STEP 2B.1 remediation invariants:
    - EXACTLY ONE training invocation per seed. The scheduler (restarts.run_schedule)
      decides which seed to attempt, invokes the training worker once, and reads the
      final health state to decide replacements. No later stage re-trains.
    - Idempotent reuse: a completed (seed, config, protocol, artifacts) run is reused,
      never re-trained, unless --force is given.
    - No fabricated test metrics: a real (non-stub) Stage E has no implementation yet and
      raises NotImplementedError instead of emitting a made-up AUC. Stub outputs are
      explicitly marked stub/synthetic/valid_for_scientific_reporting=false (R-11).

Usage (production, AFTER the strict stop is lifted):
    python run_adaptive_reid_arm.py --mode confirmatory \
        --arm_id arm_corrected_mu0.01 \
        --checkpoint ./archive/.../generator_lowest_total_loss.pth \
        --transform_mode corrected --mu 0.01 \
        --out_dir ./archive/adaptive_reid_arms/arm_corrected_mu0.01 \
        --stage a_d

Use --stub to run the full staged pipeline on generated (non-trained) records; this is
the wrapper the test suite calls to verify stage-ordering without a GPU run.
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

from adaptive_reid import constants as C
from adaptive_reid import diagnostics as diag
from adaptive_reid import health
from adaptive_reid import provenance
from adaptive_reid import restarts
from adaptive_reid import summary as summ
from adaptive_reid import topk
from adaptive_reid import pipeline

PAIR_TRAIN = 'image_pairs/image_pairs_training_10000.txt'
PAIR_VAL = 'image_pairs/image_pairs_validation_2000.txt'
PAIR_TEST = 'image_pairs/image_pairs_testing_5000.txt'

CONFIG_TEMPLATE = './config_files/config_retrainSNN.json'

# Authoritative frozen artifacts (R-12 / amendment §2). These files are SOURCE OF
# TRUTH: they are never regenerated by this driver, only hashed into provenance.
PROTOCOL_01 = 'research_agent/01_ADAPTIVE_REID_PROTOCOL.md'
PROTOCOL_01B = 'research_agent/01B_PROTOCOL_AMENDMENT.md'
FROZEN_TOPK_CSV = 'research_agent/topk_frozen_list.csv'

SIGNATURE_FILENAME = 'run_signature.json'


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def git_commit():
    try:
        out = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True)
        return out.stdout.strip()
    except Exception:
        return 'unknown'


def hashes_for(paths):
    out = {}
    for p in paths:
        out[p] = diag.sha256_file(p) if os.path.exists(p) else ''
    return out


def protocol_and_frozen_hashes():
    protocol_documents = hashes_for([PROTOCOL_01, PROTOCOL_01B])
    frozen_artifacts = hashes_for([FROZEN_TOPK_CSV])
    return protocol_documents, frozen_artifacts


def run_signature(seed, args, cfg, pair_hashes, protocol_documents, frozen_artifacts):
    """Deterministic identity of one restart attempt (used for idempotent reuse)."""
    return {
        'arm_id': args.arm_id,
        'attacker_seed': int(seed),
        'transform_mode': args.transform_mode,
        'mu': float(args.mu),
        'stochastic_lambda': float(getattr(args, 'stochastic_lambda', 0.0)),
        'generator_checkpoint_path': args.checkpoint,
        'pair_train_hash': pair_hashes.get(PAIR_TRAIN, ''),
        'pair_validation_hash': pair_hashes.get(PAIR_VAL, ''),
        'config': {
            'learning_rate': cfg.get('learning_rate'),
            'batch_size': cfg.get('batch_size'),
            'max_epochs': cfg.get('max_epochs'),
            'early_stopping': cfg.get('early_stopping'),
        },
        'protocol_documents': protocol_documents,
        'frozen_artifacts': frozen_artifacts,
        'stub': bool(args.stub),
    }


def reuse_completed_run(run_dir, signature, seed, args):
    """Return the persisted training diagnostics iff a completed, matching run exists.

    Idempotency (R-4 / BLOCKER 2B): a run whose training diagnostics, run state, and
    run signature all exist AND whose signature matches the current (seed, config,
    protocol, artifacts) is reused instead of being re-trained. For real runs the
    checkpoint must also exist. Returns None when the run must be (re)trained.
    """
    diag_path = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    runstate_path = os.path.join(run_dir, diag.RUNSTATE_FILENAME)
    sig_path = os.path.join(run_dir, SIGNATURE_FILENAME)
    if not (os.path.exists(diag_path) and os.path.exists(runstate_path)
            and os.path.exists(sig_path)):
        return None
    try:
        stored = diag.read_json(sig_path)
    except Exception:
        return None
    if stored != signature:
        return None
    if not args.stub:
        exp = 'retrain_snn_seed{}'.format(seed)
        ck = os.path.join('archive', exp, exp + '_best_network.pth')
        if not os.path.exists(ck):
            return None
    return diag.read_json(diag_path)


def stub_test_metrics(seed):
    """Deterministic synthetic Stage-E metric, EXPLICITLY marked non-scientific (R-11)."""
    return {
        'auc': 0.5 + 0.01 * (seed % 7),
        'stub': True,
        'synthetic': True,
        'valid_for_scientific_reporting': False,
        'note': 'STUB SYNTHETIC smoke metric - not a measured privacy result',
    }


def require_real_test_eval(stub):
    """Refuse to fabricate test AUC: only a stub may emit synthetic metrics (R-11)."""
    if not stub:
        raise NotImplementedError(
            'STAGE E real test evaluation is not implemented in STEP 2B.1. '
            'Refusing to fabricate a test AUC. Either run with --stub (synthetic, '
            'marked non-scientific) or implement the real frozen-test evaluation.')


def write_arm_provenance(arm_id, out_dir, summary, attempts, args, cfg, pair_hashes,
                         t0, t1, commit):
    run_states = {a['attacker_seed']: a['state'] for a in attempts}
    near_flags = {a['attacker_seed']: a['near_chance'] for a in attempts}
    seeds_attempted = [a['attacker_seed'] for a in attempts]
    rep = summary.get('representative_attacker_seed')
    protocol_documents, frozen_artifacts = protocol_and_frozen_hashes()
    record = provenance.build_arm_provenance(
        arm_id=arm_id, git_commit=commit, transform_mode=args.transform_mode,
        generator_checkpoint_path=args.checkpoint,
        generator_checkpoint_hash=diag.sha256_file(args.checkpoint) if args.checkpoint and os.path.exists(args.checkpoint) else '',
        mu=args.mu, stochastic_lambda=getattr(args, 'stochastic_lambda', 0.0),
        attacker_architecture='ResNet-50 Siamese',
        attacker_hyperparameters={
            'learning_rate': cfg.get('learning_rate'),
            'batch_size': cfg.get('batch_size'),
            'max_epochs': cfg.get('max_epochs'),
            'early_stopping': cfg.get('early_stopping'),
        },
        attacker_seeds_attempted=seeds_attempted,
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL, pair_test_path=PAIR_TEST,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        pair_test_hash=pair_hashes.get(PAIR_TEST, ''),
        representative_attacker_seed=rep,
        representative_selection_criterion='best-validation-AUC closest to median, tie=smaller seed',
        run_states=run_states, near_chance_flags=near_flags,
        run_start_timestamp=t0, run_end_timestamp=t1, schedule_name=args.mode,
        protocol_documents=protocol_documents, frozen_artifacts=frozen_artifacts)
    diag.write_json(os.path.join(out_dir, 'arm_provenance.json'), record)
    return record


def main():
    parser = argparse.ArgumentParser('Adaptive re-ID arm (frozen protocol)')
    parser.add_argument('--mode', choices=['screening', 'confirmatory'], required=True)
    parser.add_argument('--arm_id', required=True)
    parser.add_argument('--checkpoint', default=None)
    parser.add_argument('--transform_mode', default='legacy', choices=['legacy', 'corrected'])
    parser.add_argument('--mu', type=float, default=0.01)
    parser.add_argument('--stochastic_lambda', type=float, default=0.0)
    parser.add_argument('--out_dir', required=True)
    parser.add_argument('--base_config', default=CONFIG_TEMPLATE)
    parser.add_argument('--stage', choices=['a_d', 'a_e'], default='a_d',
                        help="'a_d' trains+classifies+selects+persists representative "
                             "(NO test eval). 'a_e' additionally runs Stage E test eval.")
    parser.add_argument('--stub', action='store_true',
                        help='Generate stub records instead of launching retrain_SNN.exe '
                             '(no GPU, for tests/CI). Stub test metrics are explicitly '
                             'marked synthetic and can never enter a scientific summary.')
    parser.add_argument('--force', action='store_true',
                        help='Re-train even if a matching completed run is present '
                             '(explicit override of idempotent reuse).')
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    t0 = now_iso()

    with open(args.base_config) as f:
        cfg = json.load(f)

    pair_hashes = hashes_for([PAIR_TRAIN, PAIR_VAL, PAIR_TEST])
    protocol_documents, frozen_artifacts = protocol_and_frozen_hashes()

    commit = git_commit()
    schedule = (restarts.ScreeningSchedule() if args.mode == 'screening'
                else restarts.ConfirmatorySchedule())

    # ---- Stage A + B worker: EXACTLY ONE training invocation per seed attempt ----
    def train_and_report(seed):
        exp = 'retrain_snn_seed{}'.format(seed)
        run_dir = os.path.join(args.out_dir, 'runs', exp)
        os.makedirs(run_dir, exist_ok=True)
        start = now_iso()

        signature = run_signature(seed, args, cfg, pair_hashes,
                                  protocol_documents, frozen_artifacts)
        diag.write_json(os.path.join(run_dir, SIGNATURE_FILENAME), signature)

        if not args.force:
            reused = reuse_completed_run(run_dir, signature, seed, args)
            if reused is not None:
                rec = reused
            else:
                rec = _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes)
        else:
            rec = _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes)
        rec['run_end_timestamp'] = now_iso()
        diag.write_json(os.path.join(run_dir, diag.VALIDITY_FILENAME), rec)

        state, near = health.classify_run_health(rec)
        validation_record = _validation_record_from(rec)

        diag.write_json(os.path.join(run_dir, diag.RUNSTATE_FILENAME),
                        {'state': state, 'near_chance': near, 'evaluated_test': False})
        return {'attacker_seed': seed, 'state': state, 'near_chance': near,
                'diagnostics': rec, 'validation_record': validation_record,
                'run_dir': run_dir}

    def evaluate_test(seed):
        # Stage E: evaluate the frozen TEST pairs exactly once for this completed attacker.
        require_real_test_eval(args.stub)
        run_dir = os.path.join(args.out_dir, 'runs', 'retrain_snn_seed{}'.format(seed))
        metrics = stub_test_metrics(seed)
        diag_path = os.path.join(run_dir, diag.TESTMETRICS_FILENAME)
        diag.write_json(diag_path, {**metrics, 'evaluation_timestamp': now_iso()})
        return metrics

    # The scheduler trains each attempted seed exactly once (Stage A) and, from the
    # final health state, issues ascending replacement seeds (Stage B loop).
    attempts = restarts.run_schedule(schedule, train_and_report)

    pl = pipeline.ArmPipeline(
        train_validate_and_persist=lambda seed: train_and_report(seed),
        evaluate_test=evaluate_test if args.stage == 'a_e' else None)
    # NOTE: stage_a_train_all is intentionally NOT called here - it would re-train every
    # restart (BLOCKER 2). The schedule already trained each seed exactly once.
    pl.stage_b_classify(attempts)
    rep_seed = pl.stage_c_select_representative(attempts)
    mark = {}
    pl.stage_d_persist_representative(attempts, rep_seed, mark)

    summary = summ.summarize_arm(attempts)
    summary['representative_attacker_seed'] = rep_seed
    if args.stage == 'a_e':
        pl.stage_e_evaluate_test(attempts)
        summary = summ.summarize_arm(attempts)
        summary['representative_attacker_seed'] = rep_seed

    t1 = now_iso()
    prov = write_arm_provenance(args.arm_id, args.out_dir, summary, attempts, args, cfg,
                                pair_hashes, t0, t1, commit)
    diag.write_json(os.path.join(args.out_dir, 'arm_summary.json'), summary)

    # Frozen Top-k metadata is reused from the authoritative tracked file, never
    # regenerated. Fall back to deterministic construction only if it is absent.
    try:
        frozen_path = FROZEN_TOPK_CSV
        if os.path.exists(frozen_path):
            frozen = topk.load_frozen_topk_list(frozen_path)
        else:
            frozen = topk.build_frozen_topk_list(n_patients=C.TOPK_N_PATIENTS,
                                                 seed=C.TOPK_SELECTION_SEED)
        topk.save_frozen_topk_list(os.path.join(args.out_dir, topk.FROZEN_LIST_FILENAME), frozen)
    except Exception as e:  # metadata missing -> report, do not guess
        print('Top-k list build skipped:', e)

    print('ARM COMPLETE: %s' % args.arm_id)
    print('representative_attacker_seed:', rep_seed)
    print(json.dumps(summary, indent=2, sort_keys=True))
    print('provenance:', os.path.join(args.out_dir, 'arm_provenance.json'))


def _train_once(seed, exp, run_dir, start, args, cfg, pair_hashes):
    """Launch the single training invocation for one seed and return its record.

    Raises RuntimeError instead of fabricating a record when a real run finishes without
    the protocol's machine-readable diagnostics file (no invented diagnostics).
    """
    if args.stub:
        return _stub_record(seed, start, run_dir, cfg, args, pair_hashes,
                            ck_exists=args.stub and seed % 5 != 2)
    scfg = dict(cfg)
    scfg['experiment_description'] = exp
    scfg['seed'] = seed
    scfg['transform_mode'] = args.transform_mode
    scfg['mu'] = args.mu
    scfg['stochastic_lambda'] = args.stochastic_lambda
    if args.checkpoint:
        scfg['perturbation_model_file'] = args.checkpoint
    cfg_path = os.path.join('config_files', exp + '.json')
    with open(cfg_path, 'w') as f:
        json.dump(scfg, f, indent=2)
    res = subprocess.run(
        [sys.executable, 'retrain_SNN.py', '--config_path', './config_files/',
         '--config', exp + '.json'], cwd=os.getcwd())
    os.remove(cfg_path) if os.path.exists(cfg_path) else None
    if res.returncode != 0:
        return _infra_record(seed, start, run_dir, cfg, args, pair_hashes)
    diag_path = os.path.join(run_dir, diag.VALIDITY_FILENAME)
    if os.path.exists(diag_path):
        return diag.read_json(diag_path)
    raise RuntimeError(
        'real run for seed %d finished (rc=0) without %s; refusing to fabricate '
        'training diagnostics' % (seed, diag.VALIDITY_FILENAME))


def _stub_record(seed, start, run_dir, cfg, args, pair_hashes, ck_exists=True):
    # deterministic stub: seed%5==2 marks infrastructure failure (no checkpoint)
    epochs = 8
    val_loss = [0.62 + (seed % 3) * 0.02] * epochs
    val_auc = [0.55 + (seed % 4) * 0.03] * epochs
    val_acc = [0.55] * epochs
    loss = [0.60] * epochs
    if seed % 5 == 2:
        val_loss = [0.75] * epochs
        val_auc = [0.50] * epochs
    return diag.build_training_diagnostics(
        attacker_seed=seed, transform_mode=args.transform_mode, mu=args.mu,
        stochastic_lambda=args.stochastic_lambda,
        generator_checkpoint_path=args.checkpoint or '',
        generator_checkpoint_hash=pair_hashes.get(args.checkpoint or '', ''),
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        epochs_completed=epochs, termination_reason=C.TERMINATION_EARLY_STOPPING,
        training_loss_per_epoch=loss, validation_loss_per_epoch=val_loss,
        validation_auc_per_epoch=val_auc, validation_accuracy_per_epoch=val_acc,
        best_validation_loss=min(val_loss), best_validation_loss_epoch=int(np_val_loss(val_loss)),
        best_validation_auc=max(val_auc), best_validation_auc_epoch=int(np_val_auc(val_auc)),
        any_nan_inf=False, checkpoint_exists=ck_exists, checkpoint_loadable=ck_exists,
        weights_changed_from_initialization=ck_exists,
        run_start_timestamp=start, run_end_timestamp=now_iso())


def _infra_record(seed, start, run_dir, cfg, args, pair_hashes):
    return diag.build_training_diagnostics(
        attacker_seed=seed, transform_mode=args.transform_mode, mu=args.mu,
        stochastic_lambda=args.stochastic_lambda,
        generator_checkpoint_path=args.checkpoint or '',
        generator_checkpoint_hash=pair_hashes.get(args.checkpoint or '', ''),
        pair_train_path=PAIR_TRAIN, pair_validation_path=PAIR_VAL,
        pair_train_hash=pair_hashes.get(PAIR_TRAIN, ''),
        pair_validation_hash=pair_hashes.get(PAIR_VAL, ''),
        epochs_completed=0, termination_reason=C.TERMINATION_INFRASTRUCTURE,
        training_loss_per_epoch=[], validation_loss_per_epoch=[],
        validation_auc_per_epoch=[], validation_accuracy_per_epoch=[],
        best_validation_loss=float('inf'), best_validation_loss_epoch=-1,
        best_validation_auc=0.0, best_validation_auc_epoch=-1,
        any_nan_inf=True, checkpoint_exists=False, checkpoint_loadable=False,
        weights_changed_from_initialization=False,
        run_start_timestamp=start, run_end_timestamp=now_iso())


def _validation_record_from(rec):
    return {'attacker_seed': rec['attacker_seed'],
            'validation_auc_per_epoch': list(rec['validation_auc_per_epoch']),
            'validation_loss_per_epoch': list(rec['validation_loss_per_epoch']),
            'validation_accuracy_per_epoch': list(rec['validation_accuracy_per_epoch'])}


def np_val_loss(a):
    return min(range(len(a)), key=lambda i: a[i])


def np_val_auc(a):
    return max(range(len(a)), key=lambda i: a[i])


if __name__ == '__main__':
    main()
